import { ActionType } from "redux-promise-middleware";

export const actionStrings = {
  authLogin: "AUTH_LOGIN",
  authRegister: "AUTH_REGISTER",
  authForgot: "AUTH_FORGOT",
  authConfirm: "AUTH_CONFIRM",
  authLogout: "AUTH_LOGOUT",
  counterUp: "COUNTER_UP",
  counterDown: "COUNTER_DOWN",
  counterReset: "COUNTER_RESET",
  getFavorites: "GET_FAVORITE",
  getCoffee: "GET_COFFEE",
  getNonCoffee: "GET_NON_COFFEE",
  getFood: "GET_FOOD",
  getAllProduct: "GET_ALL_PRODUCT",
  editProduct: "EDIT_PRODUCT",
  getProducts: "GET_PRODUCTS",
  getPromos: "GET_PROMO",
  addPromo: "ADD_PROMO",
  pending: `_${ActionType.Pending}`,
  fulfilled: `_${ActionType.Fulfilled}`,
  rejected: `_${ActionType.Rejected}`,
  getProfile: "GET_PROFILE",
  editPassword: "EDIT_PASSWORD",
  editProfile: "EDIT_PROFILE",
  createProduct: "CREATE_PRODUCT",
  getDetailProduct: "GET_PRODUCT_DETAIL",
};
